import os
from dotenv import load_dotenv

load_dotenv()

OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY')
OPENROUTER_MODEL_NAME = os.getenv('OPENROUTER_MODEL_NAME')
OPENROUTER_BASE_URL = os.getenv("OPENROUTER_BASE_URL")


LANGFUSE_SECRET_KEY = os.getenv('LANGFUSE_SECRET_KEY')
LANGFUSE_PUBLIC_KEY = os.getenv('LANGFUSE_PUBLIC_KEY')
LANGFUSE_BASE_URL = os.getenv('LANGFUSE_BASE_URL')